name: Detect Changes
description: Defines variables indicating the parts of the code that changed
outputs:
  isRust:
    description: True when changes happened in Rust code or related build/test files
    value: "${{ steps.diff.outputs.isRust }}"
  isTestConfig:
    description: True when changes happened in the configuration for `nextest`
    value: "${{ steps.diff.outputs.isTestConfig }}"

runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6.0.2
    - name: Detect Changes
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # pin@v3.0.2
      id: diff
      with:
        filters: |
          isRust:
            - 'crates/**'
            - 'Cargo.toml'
            - 'Cargo.lock'
            - 'rust-toolchain.toml'
            - '.github/workflows/code.yaml'
          isTestConfig:
            - '.config/nextest.toml'
